### PR TITLE
Update ember-cli to 2.18

### PR DESCRIPTION
**Pull request by siva-sundar**
Updating ember-cli to make use of Chrome headless instead of PhantomJS, since the [pipeline](https://travis-ci.org/siva-sundar/ember-hbs-minifier/builds/318990501#L764) is failing.

### CODE REVIEW

**Comment by siva-sundar** [comment]
Some of the tests are failed I am not sure why.

**Comment by mixonic** [comment]
@siva-sundar @marcoow @Turbo87 the tests appear to run back to 2.9 and before. Is there a minimum supported version of Ember, or should the tests be running for that far back?

I would like to see a release of master soon, there are fixes included that keep an app of mine pinned to master. I'm not sure if this issue or any other should be considered a blocker.

**Comment by Turbo87** [comment]
@mixonic there is no explicit minimum supported version afaik, but I'd like to support as far back as possible, and since the AST hasn't changed much there seems to be no reason why we shouldn't be able to support these older versions.

The one thing that is blocking progress right now is figuring out why some of the tests are failing when running them with headless Chrome (see https://github.com/simplabs/ember-hbs-minifier/pull/20). Once that PR is merged we can updated to latest CLI etc. (this PR) and release a new version.

**Comment by Turbo87** [comment]
> I would like to see a release of master soon, there are fixes included that keep an app of mine pinned to master. I'm not sure if this issue or any other should be considered a blocker.

🚀  I just released `master` as v0.2.0

**Pull request closed without merging**
